version: '3'

services:
  web:
    build: .
    command: python manage.py runserver
    ports:
      - "80:8000"
    environment:
      POSTGRES_HOST: 'postgres'
    hostname: 'web'

  postgres:
    image: "postgres:13.2"
    environment:
      POSTGRES_DB: 'mc_database'
      POSTGRES_USER: 'myuser'
      POSTGRES_PASSWORD: 'mysecretpassword'
    ports:
       - "5432:5432"
    hostname: 'postgres'



