# Generated by Django 4.1.7 on 2023-05-11 18:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CostGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type_group', models.IntegerField(choices=[(0, 'expense'), (1, 'income')], default=0)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Safe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('safe_type', models.CharField(choices=[('Cash', 'C1'), ('Card', 'C2'), ('Cryptocurrency', 'C3')], max_length=15)),
                ('currency', models.CharField(choices=[('UAH', 980), ('USD', 840), ('EUR', 978), ('GBP', 826), ('PLN', 985), ('CNY', 156), ('JPY', 392), ('CHF', 756), ('CZK', 203)], max_length=3)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('sum_transactions', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('cost_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.cost')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.costgroup')),
                ('safe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.safe')),
            ],
        ),
        migrations.AddField(
            model_name='cost',
            name='cost_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.costgroup'),
        ),
    ]
